"""Tests for the state change listener."""

from __future__ import annotations

from unittest.mock import MagicMock

from homeassistant.core import HomeAssistant
import pytest

from custom_components.timescaledb_exporter.db.writer import TimescaleExporter
from custom_components.timescaledb_exporter.listener import async_setup_listener


@pytest.fixture
def mock_exporter() -> MagicMock:
    """Return a mock TimescaleExporter."""
    exporter = MagicMock(spec=TimescaleExporter)
    exporter.is_excluded = MagicMock(return_value=False)
    exporter.enqueue = MagicMock(return_value=True)
    return exporter


async def test_state_change_captured(hass: HomeAssistant, mock_exporter: MagicMock) -> None:
    """Test that a state change event is captured and enqueued."""
    unsub = async_setup_listener(hass, mock_exporter)

    hass.states.async_set("sensor.temperature", "22.5", {"unit_of_measurement": "°C"})
    await hass.async_block_till_done()

    mock_exporter.enqueue.assert_called_once()
    state_change = mock_exporter.enqueue.call_args[0][0]
    assert state_change.entity_id == "sensor.temperature"
    assert state_change.state == "22.5"
    assert state_change.state_numeric == 22.5

    unsub()


async def test_state_change_non_numeric(hass: HomeAssistant, mock_exporter: MagicMock) -> None:
    """Test that non-numeric states have state_numeric=None."""
    unsub = async_setup_listener(hass, mock_exporter)

    hass.states.async_set("light.bedroom", "on", {"brightness": 255})
    await hass.async_block_till_done()

    state_change = mock_exporter.enqueue.call_args[0][0]
    assert state_change.entity_id == "light.bedroom"
    assert state_change.state == "on"
    assert state_change.state_numeric is None

    unsub()


async def test_entity_removed_skipped(hass: HomeAssistant, mock_exporter: MagicMock) -> None:
    """Test that entity removal events (new_state=None) are skipped."""
    unsub = async_setup_listener(hass, mock_exporter)

    # Set initial state, then remove it
    hass.states.async_set("sensor.temp", "20")
    await hass.async_block_till_done()
    mock_exporter.enqueue.reset_mock()

    hass.states.async_remove("sensor.temp")
    await hass.async_block_till_done()

    # Should not have been called for the removal
    mock_exporter.enqueue.assert_not_called()

    unsub()


async def test_excluded_entity_skipped(hass: HomeAssistant, mock_exporter: MagicMock) -> None:
    """Test that excluded entities are not enqueued."""
    mock_exporter.is_excluded.return_value = True

    unsub = async_setup_listener(hass, mock_exporter)

    hass.states.async_set("automation.test", "on")
    await hass.async_block_till_done()

    mock_exporter.enqueue.assert_not_called()

    unsub()


async def test_unsubscribe_stops_listening(hass: HomeAssistant, mock_exporter: MagicMock) -> None:
    """Test that unsubscribing stops event processing."""
    unsub = async_setup_listener(hass, mock_exporter)

    hass.states.async_set("sensor.a", "1")
    await hass.async_block_till_done()
    assert mock_exporter.enqueue.call_count == 1

    # Unsubscribe
    unsub()
    mock_exporter.enqueue.reset_mock()

    hass.states.async_set("sensor.b", "2")
    await hass.async_block_till_done()
    mock_exporter.enqueue.assert_not_called()


async def test_multiple_state_changes(hass: HomeAssistant, mock_exporter: MagicMock) -> None:
    """Test that multiple state changes are all captured."""
    unsub = async_setup_listener(hass, mock_exporter)

    hass.states.async_set("sensor.a", "1")
    hass.states.async_set("sensor.b", "2")
    hass.states.async_set("sensor.c", "3")
    await hass.async_block_till_done()

    assert mock_exporter.enqueue.call_count == 3

    unsub()


async def test_context_id_captured(hass: HomeAssistant, mock_exporter: MagicMock) -> None:
    """Test that context_id is captured from the state change."""
    unsub = async_setup_listener(hass, mock_exporter)

    hass.states.async_set("sensor.test", "42")
    await hass.async_block_till_done()

    state_change = mock_exporter.enqueue.call_args[0][0]
    # Context ID should be present (auto-generated by HA)
    assert state_change.context_id is not None

    unsub()
